// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.13.0
// source: internal/grpc/proto/task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ArticleTitle     string                 `protobuf:"bytes,2,opt,name=article_title,json=articleTitle,proto3" json:"article_title,omitempty"`
	ArticleUrl       string                 `protobuf:"bytes,3,opt,name=article_url,json=articleUrl,proto3" json:"article_url,omitempty"`
	Domain           string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	ProxyIp          string                 `protobuf:"bytes,5,opt,name=proxy_ip,json=proxyIp,proto3" json:"proxy_ip,omitempty"`
	ProxyPort        int32                  `protobuf:"varint,6,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	Engine           string                 `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"` // "google" | "bing"
	PreSearchQueries []string               `protobuf:"bytes,8,rep,name=pre_search_queries,json=preSearchQueries,proto3" json:"pre_search_queries,omitempty"`
	ProxyUsername    string                 `protobuf:"bytes,9,opt,name=proxy_username,json=proxyUsername,proto3" json:"proxy_username,omitempty"`  // auth for Webshare proxies
	ProxyPassword    string                 `protobuf:"bytes,10,opt,name=proxy_password,json=proxyPassword,proto3" json:"proxy_password,omitempty"` // auth for Webshare proxies
	ProxyCountry     string                 `protobuf:"bytes,11,opt,name=proxy_country,json=proxyCountry,proto3" json:"proxy_country,omitempty"`    // proxy geo country (e.g. "GB", "US") for timezone/locale matching
	ProxyTimezone    string                 `protobuf:"bytes,12,opt,name=proxy_timezone,json=proxyTimezone,proto3" json:"proxy_timezone,omitempty"` // IANA timezone (e.g. "Europe/London") derived from proxy country
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_internal_grpc_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRequest) GetArticleTitle() string {
	if x != nil {
		return x.ArticleTitle
	}
	return ""
}

func (x *TaskRequest) GetArticleUrl() string {
	if x != nil {
		return x.ArticleUrl
	}
	return ""
}

func (x *TaskRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TaskRequest) GetProxyIp() string {
	if x != nil {
		return x.ProxyIp
	}
	return ""
}

func (x *TaskRequest) GetProxyPort() int32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

func (x *TaskRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TaskRequest) GetPreSearchQueries() []string {
	if x != nil {
		return x.PreSearchQueries
	}
	return nil
}

func (x *TaskRequest) GetProxyUsername() string {
	if x != nil {
		return x.ProxyUsername
	}
	return ""
}

func (x *TaskRequest) GetProxyPassword() string {
	if x != nil {
		return x.ProxyPassword
	}
	return ""
}

func (x *TaskRequest) GetProxyCountry() string {
	if x != nil {
		return x.ProxyCountry
	}
	return ""
}

func (x *TaskRequest) GetProxyTimezone() string {
	if x != nil {
		return x.ProxyTimezone
	}
	return ""
}

type TaskResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success            bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Engine             string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	ProxyUsed          string                 `protobuf:"bytes,4,opt,name=proxy_used,json=proxyUsed,proto3" json:"proxy_used,omitempty"`
	SerpPosition       int32                  `protobuf:"varint,5,opt,name=serp_position,json=serpPosition,proto3" json:"serp_position,omitempty"` // 0 = not found
	DwellTimeSeconds   int32                  `protobuf:"varint,6,opt,name=dwell_time_seconds,json=dwellTimeSeconds,proto3" json:"dwell_time_seconds,omitempty"`
	ScrollDepthPercent int32                  `protobuf:"varint,7,opt,name=scroll_depth_percent,json=scrollDepthPercent,proto3" json:"scroll_depth_percent,omitempty"`
	InternalClicks     int32                  `protobuf:"varint,8,opt,name=internal_clicks,json=internalClicks,proto3" json:"internal_clicks,omitempty"`
	CaptchaHit         bool                   `protobuf:"varint,9,opt,name=captcha_hit,json=captchaHit,proto3" json:"captcha_hit,omitempty"`
	Error              string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	BandwidthUsedKb    int32                  `protobuf:"varint,11,opt,name=bandwidth_used_kb,json=bandwidthUsedKb,proto3" json:"bandwidth_used_kb,omitempty"` // actual bytes transferred through proxy
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_internal_grpc_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *TaskResponse) GetProxyUsed() string {
	if x != nil {
		return x.ProxyUsed
	}
	return ""
}

func (x *TaskResponse) GetSerpPosition() int32 {
	if x != nil {
		return x.SerpPosition
	}
	return 0
}

func (x *TaskResponse) GetDwellTimeSeconds() int32 {
	if x != nil {
		return x.DwellTimeSeconds
	}
	return 0
}

func (x *TaskResponse) GetScrollDepthPercent() int32 {
	if x != nil {
		return x.ScrollDepthPercent
	}
	return 0
}

func (x *TaskResponse) GetInternalClicks() int32 {
	if x != nil {
		return x.InternalClicks
	}
	return 0
}

func (x *TaskResponse) GetCaptchaHit() bool {
	if x != nil {
		return x.CaptchaHit
	}
	return false
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResponse) GetBandwidthUsedKb() int32 {
	if x != nil {
		return x.BandwidthUsedKb
	}
	return 0
}

var File_internal_grpc_proto_task_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/grpc/proto/task.proto\x12\x10searchautomation\"\x9e\x03\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rarticle_title\x18\x02 \x01(\tR\farticleTitle\x12\x1f\n" +
	"\varticle_url\x18\x03 \x01(\tR\n" +
	"articleUrl\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x19\n" +
	"\bproxy_ip\x18\x05 \x01(\tR\aproxyIp\x12\x1d\n" +
	"\n" +
	"proxy_port\x18\x06 \x01(\x05R\tproxyPort\x12\x16\n" +
	"\x06engine\x18\a \x01(\tR\x06engine\x12,\n" +
	"\x12pre_search_queries\x18\b \x03(\tR\x10preSearchQueries\x12%\n" +
	"\x0eproxy_username\x18\t \x01(\tR\rproxyUsername\x12%\n" +
	"\x0eproxy_password\x18\n" +
	" \x01(\tR\rproxyPassword\x12#\n" +
	"\rproxy_country\x18\v \x01(\tR\fproxyCountry\x12%\n" +
	"\x0eproxy_timezone\x18\f \x01(\tR\rproxyTimezone\"\x89\x03\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12\x1d\n" +
	"\n" +
	"proxy_used\x18\x04 \x01(\tR\tproxyUsed\x12#\n" +
	"\rserp_position\x18\x05 \x01(\x05R\fserpPosition\x12,\n" +
	"\x12dwell_time_seconds\x18\x06 \x01(\x05R\x10dwellTimeSeconds\x120\n" +
	"\x14scroll_depth_percent\x18\a \x01(\x05R\x12scrollDepthPercent\x12'\n" +
	"\x0finternal_clicks\x18\b \x01(\x05R\x0einternalClicks\x12\x1f\n" +
	"\vcaptcha_hit\x18\t \x01(\bR\n" +
	"captchaHit\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12*\n" +
	"\x11bandwidth_used_kb\x18\v \x01(\x05R\x0fbandwidthUsedKb2]\n" +
	"\rWorkerService\x12L\n" +
	"\vExecuteTask\x12\x1d.searchautomation.TaskRequest\x1a\x1e.searchautomation.TaskResponseB'Z%google-automation/internal/grpc/protob\x06proto3"

var (
	file_internal_grpc_proto_task_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_task_proto_rawDescData []byte
)

func file_internal_grpc_proto_task_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_task_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_task_proto_rawDesc), len(file_internal_grpc_proto_task_proto_rawDesc)))
	})
	return file_internal_grpc_proto_task_proto_rawDescData
}

var file_internal_grpc_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_grpc_proto_task_proto_goTypes = []any{
	(*TaskRequest)(nil),  // 0: searchautomation.TaskRequest
	(*TaskResponse)(nil), // 1: searchautomation.TaskResponse
}
var file_internal_grpc_proto_task_proto_depIdxs = []int32{
	0, // 0: searchautomation.WorkerService.ExecuteTask:input_type -> searchautomation.TaskRequest
	1, // 1: searchautomation.WorkerService.ExecuteTask:output_type -> searchautomation.TaskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_task_proto_init() }
func file_internal_grpc_proto_task_proto_init() {
	if File_internal_grpc_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_task_proto_rawDesc), len(file_internal_grpc_proto_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_task_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_task_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_task_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_task_proto = out.File
	file_internal_grpc_proto_task_proto_goTypes = nil
	file_internal_grpc_proto_task_proto_depIdxs = nil
}
